# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(430, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(430, 380))
        mainWindow.setMaximumSize(QtCore.QSize(430, 380))
        mainWindow.setBaseSize(QtCore.QSize(430, 325))
        self.gridLayoutWidget = QtWidgets.QWidget(mainWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 412, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.widgetVerticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.widgetVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.widgetVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.widgetVerticalLayout.setObjectName("widgetVerticalLayout")
        self.genReportBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.genReportBox.setMinimumSize(QtCore.QSize(410, 120))
        self.genReportBox.setMaximumSize(QtCore.QSize(410, 120))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setUnderline(True)
        self.genReportBox.setFont(font)
        self.genReportBox.setCheckable(True)
        self.genReportBox.setChecked(False)
        self.genReportBox.setObjectName("genReportBox")
        self.selectLocation = QtWidgets.QComboBox(self.genReportBox)
        self.selectLocation.setGeometry(QtCore.QRect(90, 60, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.selectLocation.setFont(font)
        self.selectLocation.setEditable(False)
        self.selectLocation.setObjectName("selectLocation")
        self.selectLocation.addItem("")
        self.selectLocation.addItem("")
        self.selectLocation.addItem("")
        self.selectLocation.addItem("")
        self.startDateLabel = QtWidgets.QLabel(self.genReportBox)
        self.startDateLabel.setGeometry(QtCore.QRect(20, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setUnderline(False)
        self.startDateLabel.setFont(font)
        self.startDateLabel.setObjectName("startDateLabel")
        self.browseSaveReportButton = QtWidgets.QToolButton(self.genReportBox)
        self.browseSaveReportButton.setGeometry(QtCore.QRect(340, 90, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.browseSaveReportButton.setFont(font)
        self.browseSaveReportButton.setCheckable(False)
        self.browseSaveReportButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.browseSaveReportButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.browseSaveReportButton.setObjectName("browseSaveReportButton")
        self.selectSaveReportPath = QtWidgets.QLineEdit(self.genReportBox)
        self.selectSaveReportPath.setGeometry(QtCore.QRect(100, 90, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.selectSaveReportPath.setFont(font)
        self.selectSaveReportPath.setReadOnly(False)
        self.selectSaveReportPath.setObjectName("selectSaveReportPath")
        self.selectStartDate = QtWidgets.QDateEdit(self.genReportBox)
        self.selectStartDate.setGeometry(QtCore.QRect(100, 30, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.selectStartDate.setFont(font)
        self.selectStartDate.setFrame(True)
        self.selectStartDate.setProperty("showGroupSeparator", False)
        self.selectStartDate.setCalendarPopup(True)
        self.selectStartDate.setDate(QtCore.QDate(2018, 1, 1))
        self.selectStartDate.setObjectName("selectStartDate")
        self.locationLabel = QtWidgets.QLabel(self.genReportBox)
        self.locationLabel.setGeometry(QtCore.QRect(20, 60, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setUnderline(False)
        self.locationLabel.setFont(font)
        self.locationLabel.setObjectName("locationLabel")
        self.saveReportPathLabel = QtWidgets.QLabel(self.genReportBox)
        self.saveReportPathLabel.setGeometry(QtCore.QRect(20, 90, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setUnderline(False)
        self.saveReportPathLabel.setFont(font)
        self.saveReportPathLabel.setObjectName("saveReportPathLabel")
        self.endDateLabel = QtWidgets.QLabel(self.genReportBox)
        self.endDateLabel.setGeometry(QtCore.QRect(220, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.endDateLabel.setFont(font)
        self.endDateLabel.setObjectName("endDateLabel")
        self.selectEndDate = QtWidgets.QDateEdit(self.genReportBox)
        self.selectEndDate.setGeometry(QtCore.QRect(290, 30, 110, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.selectEndDate.setFont(font)
        self.selectEndDate.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.selectEndDate.setCalendarPopup(True)
        self.selectEndDate.setDate(QtCore.QDate(2018, 1, 1))
        self.selectEndDate.setObjectName("selectEndDate")
        self.selectLocation.raise_()
        self.startDateLabel.raise_()
        self.browseSaveReportButton.raise_()
        self.selectSaveReportPath.raise_()
        self.selectStartDate.raise_()
        self.locationLabel.raise_()
        self.saveReportPathLabel.raise_()
        self.endDateLabel.raise_()
        self.selectEndDate.raise_()
        self.widgetVerticalLayout.addWidget(self.genReportBox)
        self.createSignsBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.createSignsBox.setEnabled(True)
        self.createSignsBox.setMinimumSize(QtCore.QSize(150, 160))
        self.createSignsBox.setMaximumSize(QtCore.QSize(410, 150))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setUnderline(True)
        self.createSignsBox.setFont(font)
        self.createSignsBox.setCheckable(True)
        self.createSignsBox.setChecked(False)
        self.createSignsBox.setObjectName("createSignsBox")
        self.singleOutputCheckbox = QtWidgets.QCheckBox(self.createSignsBox)
        self.singleOutputCheckbox.setGeometry(QtCore.QRect(20, 100, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.singleOutputCheckbox.setFont(font)
        self.singleOutputCheckbox.setChecked(True)
        self.singleOutputCheckbox.setObjectName("singleOutputCheckbox")
        self.useExistingReportBox = QtWidgets.QGroupBox(self.createSignsBox)
        self.useExistingReportBox.setGeometry(QtCore.QRect(10, 30, 390, 60))
        self.useExistingReportBox.setMaximumSize(QtCore.QSize(390, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.useExistingReportBox.setFont(font)
        self.useExistingReportBox.setCheckable(True)
        self.useExistingReportBox.setChecked(False)
        self.useExistingReportBox.setObjectName("useExistingReportBox")
        self.selectExistingReportPath = QtWidgets.QLineEdit(self.useExistingReportBox)
        self.selectExistingReportPath.setGeometry(QtCore.QRect(10, 30, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectExistingReportPath.setFont(font)
        self.selectExistingReportPath.setReadOnly(False)
        self.selectExistingReportPath.setObjectName("selectExistingReportPath")
        self.browseExistingReportButton = QtWidgets.QToolButton(self.useExistingReportBox)
        self.browseExistingReportButton.setGeometry(QtCore.QRect(320, 30, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browseExistingReportButton.setFont(font)
        self.browseExistingReportButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.browseExistingReportButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.browseExistingReportButton.setAutoRaise(False)
        self.browseExistingReportButton.setArrowType(QtCore.Qt.NoArrow)
        self.browseExistingReportButton.setObjectName("browseExistingReportButton")
        self.selectExistingReportPath.raise_()
        self.browseExistingReportButton.raise_()
        self.genReportBox.raise_()
        self.genReportBox.raise_()
        self.selectSaveSignsPath = QtWidgets.QLineEdit(self.createSignsBox)
        self.selectSaveSignsPath.setGeometry(QtCore.QRect(100, 130, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.selectSaveSignsPath.setFont(font)
        self.selectSaveSignsPath.setReadOnly(False)
        self.selectSaveSignsPath.setObjectName("selectSaveSignsPath")
        self.browseSaveSignsButton = QtWidgets.QToolButton(self.createSignsBox)
        self.browseSaveSignsButton.setGeometry(QtCore.QRect(330, 130, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.browseSaveSignsButton.setFont(font)
        self.browseSaveSignsButton.setCheckable(False)
        self.browseSaveSignsButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.browseSaveSignsButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.browseSaveSignsButton.setObjectName("browseSaveSignsButton")
        self.saveSignsPathLabel = QtWidgets.QLabel(self.createSignsBox)
        self.saveSignsPathLabel.setGeometry(QtCore.QRect(20, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setUnderline(False)
        self.saveSignsPathLabel.setFont(font)
        self.saveSignsPathLabel.setObjectName("saveSignsPathLabel")
        self.widgetVerticalLayout.addWidget(self.createSignsBox)
        self.startExitLayout = QtWidgets.QGridLayout()
        self.startExitLayout.setObjectName("startExitLayout")
        self.exitButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.exitButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.startExitLayout.addWidget(self.exitButton, 0, 1, 1, 1)
        self.StartButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.StartButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.startExitLayout.addWidget(self.StartButton, 0, 0, 1, 1)
        self.widgetVerticalLayout.addLayout(self.startExitLayout)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Auto Schedule"))
        self.genReportBox.setTitle(_translate("mainWindow", "Generate Destiny Report"))
        self.selectLocation.setItemText(0, _translate("mainWindow", "ABSW"))
        self.selectLocation.setItemText(1, _translate("mainWindow", "Belmont"))
        self.selectLocation.setItemText(2, _translate("mainWindow", "Golden Bear Center"))
        self.selectLocation.setItemText(3, _translate("mainWindow", "San Francisco Center"))
        self.startDateLabel.setText(_translate("mainWindow", "Start Date:"))
        self.browseSaveReportButton.setText(_translate("mainWindow", "Browse"))
        self.selectSaveReportPath.setText(_translate("mainWindow", "C:\\"))
        self.locationLabel.setText(_translate("mainWindow", "Location:"))
        self.saveReportPathLabel.setText(_translate("mainWindow", "Save Path:"))
        self.endDateLabel.setText(_translate("mainWindow", "End Date:"))
        self.createSignsBox.setTitle(_translate("mainWindow", "Create Signs"))
        self.singleOutputCheckbox.setText(_translate("mainWindow", "Single File Output"))
        self.useExistingReportBox.setTitle(_translate("mainWindow", "Use existing Destiny Report"))
        self.selectExistingReportPath.setText(_translate("mainWindow", "C:\\"))
        self.browseExistingReportButton.setText(_translate("mainWindow", "Browse"))
        self.selectSaveSignsPath.setText(_translate("mainWindow", "C:\\"))
        self.browseSaveSignsButton.setText(_translate("mainWindow", "Browse"))
        self.saveSignsPathLabel.setText(_translate("mainWindow", "Save Path:"))
        self.exitButton.setText(_translate("mainWindow", "Exit"))
        self.StartButton.setText(_translate("mainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QWidget()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

